version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_sismico
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: sistema_sismico
    ports:
      - "3306:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: